public with sharing class CampaignConstant {
    public static final String ALGORITHMNAME = 'AES256';   	
    //Source
    public static final String SOURCE_SALESFORCE = 'Salesforce';
    public static final String SOURCE_QC = 'QC';

    //Status
    public static final String STATUS_PLANED = 'Planned';
    public static final String STATUS_IN_PROGRESS = 'In Progress';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_ABORTED = 'Aborted';
    
    //Record Type
    public static final String RECORDTYPE_B2B_MARKETING = 'B2B_Marketing';
    public static final String RECORDTYPE_PROMOTION = 'Promotion';


    public static final String CONDITION_TYPE_PAYMENT = 'Payment';
    public static final String CONDITION_TYPE_SPENDING = 'Spending';

}