public with sharing class CaseConstant {
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_WORKING = 'Working';
    public static final String STATUS_WAITING_FOR_CUSTOMER_RESPONSE = 'Waiting for Customer Response';
    public static final String STATUS_ASSIGNED_TO_DEV = 'Assigned to Dev';
    public static final String STATUS_DEV_PROCESSING = 'Dev Processing';
    public static final String STATUS_WAITING_AOM_FEEDBACK = 'Waiting AOM feedback';
    public static final String STATUS_CLOSED = 'Closed';


    public static final String OPERATOR_CONTAINS = 'Contains';
    public static final String OPERATOR_NOT_CONTAINS = 'Not Contains';
    public static final String OPERATOR_EQUAL = 'Equal';
    public static final String OPERATOR_NOT_EQUAL = 'Not Equal';
}