public class cc_Messages {
	public static string Sharing_Percent_RecordType_Global = 'Global';
    public static string Sharing_Percent_RecordType_Local = 'Local';
    public static string Sharing_Percent_RecordType_Is_Direct = 'Is Direct';
    public static string Sharing_Percent_RecordType_Industry = 'Industry';
    
    public static string Agency_Local_Agency = 'Local Agency';
    public static string Agency_Global_Agency = 'Global Agency';
     public static string Agency_Direct_Business = 'Direct Business';
    
    public static string Account_Executive = 'Account Executive';
    public static string Account_Director = 'Account Director';
    public static string Account_Supervisor = 'Account Supervisor';
    public static string Account_Manager = 'Account Manager';
    public static string Account_Admin = 'Account Admin';
    
    public static string Ads_Total_Local = 'Ads Total Local';
    public static string Ads_Total_Direct = 'Ads Total Direct';
    public static string Ads_Total_Global = 'Ads Total Global';
    
 	public static string Total_Local = 'Total Local';
    public static string Total_Direct = 'Total Direct';
    public static string Total_Global = 'Total Global';
    
}