public  class ClientSharingConstant {
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_IN_PROGRESS = 'In Progress';
    public static final String STATUS_WAITING_FOR_APPROVAL = 'Waiting for Approval';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_CANCELED = 'Canceled';

    public static final String ROWCAUSE = 'Client_Sharing__c';
}