public class CouponConstant {
    public static final String ALGORITHMNAME = 'AES256';   	 
    
    //Source
    public static final String SOURCE_SALESFORCE = 'Salesforce';
    public static final String SOURCE_QC = 'QC';

    //Status
    public static final String STATUS_DRAFT = 'Draft';
    public static final String STATUS_ACTIVE = 'Active';
    public static final String STATUS_DEACTIVATED = 'Deactivated';
    public static final String STATUS_USED = 'Used';
    
}