public with sharing class KPIConstant {

    public static final String MANAGER_LEVEL_1 = 'Level 1';
    public static final String MANAGER_LEVEL_2 = 'Level 2';
    public static final String MANAGER_LEVEL_3 = 'Level 3';

    public static final String SALE_TEAM_GLOBAL_AGENCY = 'Global Agency';
    public static final String SALE_TEAM_LOCAL_AGENCY = 'Local Agency';
    public static final String SALE_TEAM_DIRECT = 'Direct';   
    
    public static final String TEAM_TARGET_RECORDTYPE = 'Sale_KPI';   
    public static final String MANAGER_TARGET_RECORDTYPE = 'Sale_Manager_KPI';   
    
    public static final String STATUS_APPROVED = 'Approved';
    public static final String STATUS_NEW = 'New';
    public static final String STATUS_PLANNING = 'Planning';
    public static final String STATUS_PENDING_APPROVAL = 'Pending Approval';
    public static final String STATUS_CLOSED = 'Closed';
    
    
}