public class QCAccountConstant {
     //Type 
     public static final String TYPE_NORMAL = 'Normal';
     public static final String TYPE_AGENCY = 'Agency';
     public static final String TYPE_MCC = 'MCC';
     public static final String TYPE_INTERNAL = 'Internal';
     public static final String TYPE_EXTERNAL = 'External';


    //QC Account Source
    public static final String SOURCE_QC = 'QC';
    public static final String SOURCE_SKINTOOL = 'Skintool';
    public static final String SOURCE_SALESFORCE = 'Salesforce';
    public static final String SOURCE_GAMESTORE = 'Gamestore';
    public static final String SOURCE_MOBILESKIN = 'MobileSkin';


     //QC Account Agency
     public static final String AGENCY_OTHER = 'Other';
     public static final String AGENCY_CLIENT = 'Client';
     public static final String AGENCY_PERSON_ACCOUNT = 'Person Account';
     public static final String AGENCY_LOCAL_AGENCY = 'Local Agency';
     public static final String AGENCY_GLOBAL_AGENCY = 'Global Agency';

     public static final String STATUS_ACTIVE = 'Active';
     
}