public class TransactionTypeConstant {
    public static final String ALGORITHMNAME = 'AES256';   
    public static final String DISCOUNT_AMOUNT = 'DISCOUNT_AMOUNT';
    public static final String SPECIAL_DISCOUNT_AMOUNT = 'SPECIAL_DISCOUNT_AMOUNT';
    public static final String SPENDING_BONUS = 'SPENDING_BONUS';
    public static final String PROMOTION = 'PROMOTION';
    public static final String COMPENSATION = 'COMPENSATION';
    public static final String TEST_AMOUNT = 'TEST_AMOUNT';
    public static final String ADVANCE = 'ADVANCE';
    public static final String PAID_AMOUNT = 'PAID_AMOUNT';
    public static final String PROMOTION_WITH_CONDITION = 'PROMOTION_WITH_CONDITION';
    public static final String MONTHLY_SPENDING_BONUS = 'MONTHLY_SPENDING_BONUS';
}