public with sharing class TransferRequestConstant {
    public static final String TRANSFER_PURPOSE_TRANSFER_OWNER = 'Transfer Owner';
    public static final String TRANSFER_PURPOSE_TRANSFER_DATA = 'Transfer Data';
    public static final String TRANSFER_PURPOSE_TRANSFER_ADS_OP = 'Transfer Ads Op';


    public static final String TRANSFER_TYPE_SALE = 'Sale';
    public static final String TRANSFER_TYPE_SUPPORT = 'Support';
    public static final String TRANSFER_TYPE_INDUSTRY = 'Industry';

    public static final String TRANSFER_OBJECT_SPENDING = 'Spending';
    public static final String TRANSFER_OBJECT_PAYMENT = 'Payment';


    public static final String STATUS_NEW = 'New';
    public static final String STATUS_WAITING_FOR_APPROVE = 'Waiting for Approve';
    public static final String STATUS_COMPLETED = 'Completed';

    public static final String APPROVAL_STATUS_NEW = 'New';
    public static final String APPROVAL_STATUS_SENT = 'Sent';
    public static final String APPROVAL_STATUS_RECALL = 'Recall';
    public static final String APPROVAL_STATUS_APPROVED = 'Approved';
    public static final String APPROVAL_STATUS_REJECTED = 'Rejected';

}